### ISSUE TITLE
Assigning constant value to a module variable from another module makes variable 'int'.

### ISSUE THREAD

**Issue by armoha** [phu54321/epScript#3]
### example code)
main.eps
```javascript
import module;

function afterTriggerExec() {
    module.a = 1;
    module.main();
    py_print(module.a, py_type(module.a));
}
```

module.eps
```javascript
var a = 1;

function main() {
    var b = 0;
    a = b;
}
```

> 1 <class 'int'>
File "main.eps", line 5, in afterTriggerExec
    module.main();
  File "module.eps", line 5, in f_main
    a = b;
 TypeError: unsupported operand type(s) for <<: 'int' and 'EUDVariable'

It raises TypeError, but when *module.main();* is called before *module.a = 1;*, the compile is successful and module.a is still an 'int', causing unexpected behavior.
```javascript
import module;

function afterTriggerExec() {
    module.main();
    module.a = 1;
    py_print(module.a, py_type(module.a));
}
```
> 1 <class 'int'>
> [Stage 1/3] CollectObjects
>  \- Collected 681 / 681 objects
[Stage 2/3] AllocObjects
 \- Preprocessed 681 / 681 objects
 \- Allocating objects..
[Stage 3/3] ConstructPayload
 \- Written 681 / 681 objects
Output scenario.chk : 0.909MB
Done!

**Comment by armoha** [comment]
To workaround this, use *SetVariables(module.a, 1);*.
> <eudplib.core.variable.eudv.EUDVariable object at 0x03D42990> <class 'eudplib.core.variable.eudv.EUDVariable'>

**Comment by phu54321** [comment]
wontfix. This seems to be out of epScript's ability
