### ISSUE TITLE
/= doesn't work on EUDArray, while *= do

### ISSUE THREAD

**Issue by armoha** [phu54321/epScript#6]
```javascript
function afterTriggerExec()
{
    const a = EUDArray(8);
    a[0] *= 2;
    a[1] /= 2;
}
/*
line 5, in afterTriggerExec
    a[1] /= 2;
AttributeError: '_ARRW' object has no attribute '__ifloordiv__'
*/
```

In TriggerEditor of EUD Editor 2, `P variable` is EUDArray with length 8. Action `SetVariable` uses +=, -=, *=, /= for arithmetic.

**Comment by phu54321** [comment]
This issue has been resolved in https://github.com/phu54321/epScript/commit/1c2febd4b85626c7eded14c469f1ef73aab14507.

Not just yet merged w/ euddraft I think.
